name: school_mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: 6.1.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  image_picker: ^1.0.4
  go_router: ^9.0.3
  flutter_animate: ^4.2.0+1
  flutter_spinkit: ^5.1.0
  badges: ^3.1.1
  flutter_svg: 2.0.7
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.4.0
  page_transition: ^2.1.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  getwidget: ^4.0.0
  get_it: ^7.6.4
  flutter_native_splash: ^2.3.9
  gap: ^3.0.1
  dotted_border: ^2.1.0
  fluttertoast: ^8.2.4
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
     - assets/logo/
  #   - images/a_dot_ham.jpeg